import type { Metadata } from "next";
import { NavBar } from "@/components/ui/NavBar";
import { Footer } from "@/components/ui/Footer";
import { CorporateBenefitsForm } from "@/components/company/CorporateBenefitsForm";

export const metadata: Metadata = {
  title: "Corporate Home Benefits Program for Employers | HCMG",
  description: "Help employees navigate homeownership with HCMG's zero-direct-cost Corporate Home Benefits Program, including education, licensed guidance, branded resources, and employer reporting.",
  alternates: { canonical: "https://hcmgloans.com/company-partners" },
};

const EMPLOYEE_BENEFITS = ["Homebuying guidance and pre-qualification", "Refinance, HELOC, and home-equity reviews", "First-time buyer education", "Down payment assistance navigation where available", "VA loan education for military-connected employees", "Annual mortgage and home-equity checkups"];
const EMPLOYER_BENEFITS = ["Zero direct cost, subsidy, or payroll impact", "Turnkey launch with an HR communications toolkit", "A dedicated, co-branded employee landing page", "Quarterly utilization reporting", "Virtual or onsite educational events", "A meaningful recruiting and retention story"];
const FAQS = [
  ["What does the program cost the employer?", "The program is designed with zero direct cost to the employer: no per-employee fee, payroll deduction, or employer subsidy. HCMG earns revenue through mortgage origination when an eligible employee chooses to complete a loan."],
  ["What does HR need to manage?", "HCMG provides the rollout materials, co-branded employee page, education, and ongoing support. HR helps select communication channels and introduce the benefit; HCMG manages the mortgage engagement."],
  ["Is employee participation required?", "No. Employees choose whether to engage and affirmatively provide their information. The employer does not enroll employees into mortgage services or make lending decisions."],
  ["What services can employees access?", "Available support may include homebuying education, pre-qualification, refinance and equity reviews, first-time buyer resources, VA education, and navigation of eligible state or local assistance programs."],
  ["Can HCMG support a distributed workforce?", "HCMG can serve employees in markets where the company and assigned loan officer are appropriately licensed. Availability, products, and program features vary by state."],
  ["Is this limited by region?", "The employer benefit can be offered broadly, but mortgage services are available only in states where HCMG and the assigned loan officer are appropriately licensed. Product and program availability varies by location."],
  ["Are there minimums for company size?", "No. There is no required minimum company size to start a conversation. We tailor implementation to the workforce, locations, and expected level of employee engagement."],
  ["Are there loan size minimums?", "No. HCMG does not set a special loan-size minimum for participation in the Corporate Home Benefits Program. Standard product, investor, eligibility, and lawful lending requirements still apply."],
  ["How is utilization reported?", "Employers can receive periodic, aggregate engagement reporting designed to show program utilization while protecting individual employee financial and mortgage information."],
];

export default function CompanyPartnersPage() {
  return <main>
    <NavBar />
    <section className="relative overflow-hidden bg-brand-dark text-white">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_20%,rgba(243,112,33,.42),transparent_35%),radial-gradient(circle_at_10%_90%,rgba(255,152,71,.14),transparent_32%)]" />
      <div className="container-shell relative grid gap-14 py-20 lg:grid-cols-[1.1fr_.75fr] lg:items-center lg:py-24">
        <div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent-light">HCMG’s Corporate Home Benefits Program</p><h1 className="mt-5 text-4xl font-extrabold leading-[1.06] tracking-tight sm:text-5xl lg:text-6xl">Make homeownership support part of your benefits strategy.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Give employees trusted mortgage education, licensed local guidance, and a clear path through homeownership—at zero direct cost to your company.</p><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-white/80"><span>✓ Turnkey for HR</span><span>✓ Voluntary for employees</span><span>✓ Built for measurable engagement</span></div></div>
        <div className="rounded-[2rem] border border-white/15 bg-white p-6 text-ink shadow-2xl sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent">For HR and benefits leaders</p><h2 className="mt-2 text-2xl font-extrabold">Explore a company partnership</h2><p className="mb-5 mt-2 text-sm leading-6 text-muted">Tell us about your workforce. We’ll show you how the program can fit your benefits strategy.</p><CorporateBenefitsForm compact /></div>
      </div>
    </section>

    <section className="border-b border-line bg-white py-10"><div className="container-shell grid gap-5 text-center sm:grid-cols-3"><div><p className="text-4xl font-extrabold text-brand">43.2%</p><p className="mt-2 text-sm text-muted">of surveyed employees live paycheck to paycheck</p></div><div><p className="text-4xl font-extrabold text-brand">90.9%</p><p className="mt-2 text-sm text-muted">say homebuying affects daily productivity</p></div><div><p className="text-4xl font-extrabold text-brand">75%</p><p className="mt-2 text-sm text-muted">would be more likely to join a company offering mortgage benefits</p></div><p className="sm:col-span-3 text-[11px] leading-5 text-muted/60">Third-party 2025 PollFish workforce survey of 1,000 U.S. consumers employed at organizations with 1,000+ employees. These are not HCMG program results.</p></div></section>

    <section className="section-pad bg-sand"><div className="container-shell"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">One benefit. Value on both sides.</p><h2 className="mt-3 text-3xl font-extrabold text-ink lg:text-4xl">Financial confidence for employees. A stronger benefits story for employers.</h2></div><div className="mt-12 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-line bg-white p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-accent">What employees get</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{EMPLOYEE_BENEFITS.map(x=><div key={x} className="flex gap-3 text-sm leading-6 text-ink"><span className="text-accent">✓</span>{x}</div>)}</div></div><div className="rounded-3xl bg-brand p-8 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-accent-light">What employers get</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{EMPLOYER_BENEFITS.map(x=><div key={x} className="flex gap-3 text-sm leading-6 text-white/80"><span className="text-accent-light">✓</span>{x}</div>)}</div></div></div></div></section>

    <section className="section-pad bg-white"><div className="container-shell grid items-center gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">Why HCMG</p><h2 className="mt-3 text-3xl font-extrabold text-ink lg:text-4xl">Local expertise, multi-lender access, and technology built around people.</h2><p className="mt-5 text-base leading-8 text-muted">Employees should not have to navigate one of life’s largest financial decisions through a generic call center. HCMG combines licensed human guidance with a modern, low-friction experience.</p></div><div className="grid gap-4 sm:grid-cols-2">{[["Multi-lender access","More room to find an appropriate fit than a single captive rate sheet."],["Licensed guidance","Employees connect with a real mortgage professional in an eligible market."],["24/7 education","Digital resources answer common questions and prepare employees for human guidance."],["Employer-first reporting","Aggregate utilization insights help benefits leaders understand engagement."]].map(([h,b])=><div key={h} className="rounded-3xl border border-line bg-sand p-6"><h3 className="font-extrabold text-ink">{h}</h3><p className="mt-2 text-sm leading-6 text-muted">{b}</p></div>)}</div></div></section>

    <section className="section-pad border-y border-line bg-sand"><div className="container-shell"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">Turnkey implementation</p><h2 className="mt-3 text-3xl font-extrabold text-ink lg:text-4xl">From agreement to employee launch.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-4">{[["01","Discover","Align on workforce, locations, and program goals."],["02","Configure","Build the branded page, materials, and routing."],["03","Launch","Introduce the benefit through your selected HR channels."],["04","Measure","Review aggregate engagement and optimize quarterly."]].map(([n,h,b])=><div key={n} className="rounded-3xl border border-line bg-white p-6"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand text-xs font-extrabold text-white">{n}</span><h3 className="mt-5 font-extrabold text-ink">{h}</h3><p className="mt-2 text-sm leading-6 text-muted">{b}</p></div>)}</div></div></section>

    <section className="section-pad bg-brand-dark text-white"><div className="container-shell grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-accent-light">Schedule a meeting</p><h2 className="mt-3 text-3xl font-extrabold lg:text-4xl">See how the program could work for your company.</h2><p className="mt-5 max-w-xl leading-8 text-white/70">Choose a preferred time to meet with our Corporate Home Benefits team. We’ll discuss your workforce, rollout options, and the questions your HR team needs answered.</p></div><div className="rounded-3xl bg-white p-6 text-ink shadow-2xl sm:p-8"><CorporateBenefitsForm variant="meeting" /></div></div></section>

    <section className="section-pad bg-white"><div className="container-shell max-w-4xl"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">Frequently asked questions</p><h2 className="mt-3 text-3xl font-extrabold text-ink lg:text-4xl">Corporate Home Benefits FAQ</h2></div><div className="mt-10 divide-y divide-line rounded-3xl border border-line px-6 shadow-soft sm:px-8">{FAQS.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-bold text-ink"><span>{q}</span><span className="text-xl text-accent transition group-open:rotate-45">+</span></summary><p className="mt-3 pr-8 text-sm leading-7 text-muted">{a}</p></details>)}</div></div></section>

    <section className="bg-brand px-5 py-20 text-center text-white"><div className="mx-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent-light">A better benefit starts here</p><h2 className="mt-4 text-3xl font-extrabold lg:text-5xl">Help employees move from housing stress to a plan.</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-white/70">Bring HCMG’s Corporate Home Benefits Program to your workforce with no direct employer cost and a rollout built to be easy for HR.</p><div className="mx-auto mt-8 max-w-xl rounded-3xl bg-white p-6 text-left text-ink"><CorporateBenefitsForm /></div></div></section>
    <Footer />
  </main>;
}
